language: python
cache: pip
notifications:
  email: false
python:
  - "3.5"
  - "3.6"
os:
  - linux
# command to install dependencies
install:
  - pip install numpy
  - python setup.py sdist
  - travis_wait pip install dist/sumo-*.tar.gz
# command to run tests
script:
  - python -m unittest discover tests
